#!/bin/bash
# tired of typing "sudo dnf install".

echo -e "\v\ts. Search, i. Install: "
  read action
  case $action in
    s)
      dnf search $@ ;;#${args[*]} ;;
    i)
      sudo dnf install $@ ;;
  esac

